version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./provision/mysql/volumes:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: redis:3.0.7
    ports:
      - "6379:6379"
